# Generated by Django 4.1 on 2023-04-08 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'managed': True, 'ordering': ['complete']},
        ),
        migrations.AlterModelTable(
            name='task',
            table='Task',
        ),
    ]
