# Generated by Django 4.1 on 2023-04-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_options_alter_task_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'managed': True, 'ordering': ['complete', 'priority', 'date']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='date',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
