# Generated by Django 4.1 on 2023-04-18 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_task_options_rename_created_task_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'managed': True, 'ordering': ['complete', '-priority', 'date']},
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, default='Category', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='todo.category'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
